services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_DATABASE
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_PORT=$POSTGRES_DB_PORT
    container_name: listai-postgres
    volumes:
      - listai_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
#  pgadmin:
#    image: dpage/pgadmin4:8.6
#    container_name: listai-pgadmin4
#    restart: always
#    ports:
#      - "$PGADMIN_PORT:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
#      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
#    depends_on:
#      db:
#        condition: service_started
#    volumes:
#      - listai_pgadmin4:/var/lib/pgadmin
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: listai-redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listai-nest
    ports:
      - '$PORT:3000'
    command: bash -c "npm run build && npm run start"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

volumes:
  listai_postgres:
  listai_pgadmin4:
