services:
  db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_DATABASE
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_DB_PORT=$POSTGRES_DB_PORT
    container_name: bartar-postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: bartar-pgadmin4
    restart: always
    ports:
      - "$PGADMIN_PORT:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    depends_on:
      db:
        condition: service_started
    volumes:
      - pgadmin4:/var/lib/pgadmin

  redis:
    image: redis:7.2.0
    restart: always
    container_name: bartar-redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bartar-nest
    ports:
      - '$PORT:$PORT'
    command: npm run start:dev
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

volumes:
  postgres:
  pgadmin4:
